app/bp_main/models.py
# -*- coding:utf-8 -*-
"""
    :author: Albert Li
    :copyright: © 2019 Albert Li 
    :time: 2020/4/15 21:30
"""
import arrow

from app.db.model import BaseModel
from app.extensions import db


class Banner(db.Model, BaseModel):
    """banner表"""

    __tablename__ = "mz_banner"
    id = db.Column(
        db.Integer, primary_key=True, autoincrement=True, nullable=False
    )  # id，主键，
    desc = db.Column(db.String(64))  # banner描述
    image_url = db.Column(db.String(255))  # 图片链接
    link_url = db.Column(db.String(255))  # 跳转链接
    create_time = db.Column(
        db.BigInteger, nullable=False, index=True, default=arrow.utcnow().timestamp
    )  # 文章创建时间
    update_time = db.Column(db.BigInteger)  # 最近一次的更新时间
    is_used = db.Column(db.Integer, default=0)  # 是否在使用中，0-不在使用 1-使用中

    @classmethod
    def query_used(cls):
        """查询正在使用中的banner """
        return cls.query.filter_by(is_used=1).all()


class SiteDesc(db.Model, BaseModel):
    """网站说明表"""

    __tablename__ = "mz_site_desc"
    id = db.Column(
        db.Integer, primary_key=True, autoincrement=True, nullable=False
    )  # id，主键，自增
    body = db.Column(db.Text, nullable=False)  # markdown格式的文章内容
    create_time = db.Column(
        db.BigInteger, nullable=False, index=True, default=arrow.utcnow().timestamp
    )  # 文章创建时间
    update_time = db.Column(db.BigInteger)  # 文章最近一次的更新时间

app/bp_main/forms.py
# -*- coding:utf-8 -*-
"""
    :author: Albert Li
    :copyright: © 2019 Albert Li 
    :time: 2020/4/15 21:38
"""
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired


class SiteDescForm(FlaskForm):
    """网站描述表单"""

    body = TextAreaField(label=u"内容", validators=[DataRequired()])
    submit = SubmitField(label=u"提交")

app/bp_main/__init__.py
# -*- coding:utf-8 -*-
"""
    :author: Albert Li
    :copyright: © 2019 Albert Li
    :time: 2019/11/6 9:44 
"""
from flask import Blueprint

main_bp = Blueprint(
    "main",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="",
)

from . import routes

app/bp_main/routes.py
# -*- coding:utf-8 -*-
"""
    :author: Albert Li
    :copyright: © 2019 Albert Li
    :time: 2019/11/6 10:06 
"""
from pathlib import Path

import arrow
from flask import (
    render_template,
    request,
    current_app,
    redirect,
    url_for,
    jsonify,
    Response,
)
from flask_login import login_required, current_user

from app.bp_main.forms import SiteDescForm
from app.bp_main.models import Banner, SiteDesc
from app.bp_work.models import Article, Category, Tag
from app.extensions import csrf
from app.utils.times import timestamp_to_str
from app.utils.uploads import (
    upload_image,
    get_local_image,
    remove_unused_image_from_local,
)
from . import main_bp


@main_bp.route("/banner/image/<string:image_name>/", methods=["GET"])
@csrf.exempt  # 此路由去除 csrf 保护
def get_banner_image(image_name: str):
    """ 获取banner图片

    :param image_name: 图片名称
    """
    # 图片的完整路径
    image_path = Path.joinpath(
        current_app.config["MYZONE_IMAGE_BANNER_DIR"], image_name
    )
    with open(str(image_path), "rb") as f:
        resp = Response(f.read(), mimetype="image/png")
    return resp


@main_bp.route("/", methods=["GET"])
def index():
    """首页"""
    banners = Banner.query_used()
    page = request.args.get("page", 1, type=int)  # 指定的页码
    per_page = current_app.config["MYZONE_ARTICLE_PER_PAGE"]  # 每页的文章数
    pagination = Article.query_order_by_createtime(page, per_page=per_page)  # 创建分页器对象
    articles = pagination.items  # 从分页器中获取查询结果
    categories = Category.query_all()
    tags = Tag.query_all()
    return render_template(
        "main/index.html",
        pagination=pagination,
        articles=articles,
        categories=categories,
        tags=tags,
        timestamp_to_strftime=timestamp_to_str,
        func_id=0,
        banners=banners,
    )


@main_bp.route("/channel/<int:channel_id>/", methods=["GET"])
def get_articles_by_channel(channel_id: int):
    """分页查询指定专栏的文章"""
    page = request.args.get("page", 1, type=int)  # 指定的页码
    per_page = current_app.config["MYZONE_ARTICLE_PER_PAGE"]  # 每页的文章数
    pagination = Article.query_by_channel(
        channel_id, page, per_page=per_page
    )  # 创建分页器对象
    articles = pagination.items  # 从分页器中获取查询结果
    categories = Category.query_by_channel(channel_id)
    tags = Tag.query_all()
    return render_template(
        "main/index.html",
        pagination=pagination,
        articles=articles,
        categories=categories,
        tags=tags,
        timestamp_to_strftime=timestamp_to_str,
        func_id=channel_id,
    )


@main_bp.route("/category/<int:category_id>/", methods=["GET"])
def get_articles_by_category(category_id: int):
    """分页查询指定分类的文章"""
    page = request.args.get("page", 1, type=int)  # 指定的页码
    per_page = current_app.config["MYZONE_ARTICLE_PER_PAGE"]  # 每页的文章数
    pagination = Article.query_by_category(
        category_id, page, per_page=per_page
    )  # 创建分页器对象
    articles = pagination.items  # 从分页器中获取查询结果
    category = Category.query_by_id(category_id)
    tags = Tag.query_all()
    return render_template(
        "main/index.html",
        pagination=pagination,
        articles=articles,
        categories=category.channel.categories,
        tags=tags,
        timestamp_to_strftime=timestamp_to_str,
        func_id=category.channel_id,
    )


@main_bp.route("/category/<int:tag_id>/", methods=["GET"])
def get_articles_by_tag(tag_id: int):
    """分页查询拥有指定标签的文章"""
    page = request.args.get("page", 1, type=int)  # 指定的页码
    per_page = current_app.config["MYZONE_ARTICLE_PER_PAGE"]  # 每页的文章数
    tag = Tag.query_by_id(tag_id)
    pagination = tag.query_articles(page, per_page=per_page)  # 创建分页器对象
    articles = pagination.items  # 从分页器中获取查询结果
    categories = Category.query_all()
    tags = Tag.query_all()
    return render_template(
        "main/index.html",
        pagination=pagination,
        articles=articles,
        categories=categories,
        tags=tags,
        timestamp_to_strftime=timestamp_to_str,
        func_id=-1,
    )


@main_bp.route("/search/", methods=["GET"])
@csrf.exempt  # 此路由去除 csrf 保护
def get_articles_by_fullsearch():
    """全文搜索"""
    keyword = request.args.get("keyword", type=str)
    page = request.args.get("page", 1, type=int)  # 指定的页码
    if not keyword:
        return redirect(url_for(".index"))
    per_page = current_app.config["MYZONE_ARTICLE_PER_PAGE"]  # 每页的文章数
    pagination = Article.query_in_full_by_key(
        keyword, page, per_page=per_page
    )  # 创建分页器对象
    articles = pagination.items  # 从分页器中获取查询结果
    categories = Category.query_all()
    tags = Tag.query_all()
    return render_template(
        "main/index.html",
        pagination=pagination,
        articles=articles,
        categories=categories,
        tags=tags,
        timestamp_to_strftime=timestamp_to_str,
        func_id=-1,
    )


@main_bp.route("/about/", methods=["GET"])
def show_about():
    """关于本站"""
    site_desc = SiteDesc.query_by_id(1)
    return render_template("main/about.html", site_desc=site_desc, channel_id=3)


@main_bp.route("/about/edit/", methods=["GET", "POST"])
@login_required
def edit_about():
    """编辑网站说明"""
    if current_user.role_id != 3:
        # 只有管理员才能编辑网站说明
        return redirect(url_for(".index"))
    site_desc = SiteDesc.query_by_id(1)

    form = SiteDescForm()
    if form.validate_on_submit():
        site_desc.body = form.body.data
        body_html = request.form[
            "my-editormd-html-code"
        ]  # html 格式的文章內容，由 Editor.MD 自动生成的 textarea
        # site_desc.body_html = body_html
        site_desc.update_time = arrow.utcnow().timestamp
        site_desc.update()
        remove_unused_image_from_local(
            current_app.config["MYZONE_IMAGE_ABOUT_DIR"], body_html, 2
        )
        return redirect(url_for(".show_about"))
    form.body.data = site_desc.body
    return render_template("main/edit_about.html", form=form)


@main_bp.route("/about/upload-image/", methods=["POST"])
@login_required
@csrf.exempt  # 此路由去除 csrf 保护
def upload_about_image():
    """上传文章中的图片"""
    image_file = request.files.get("editormd-image-file")
    result: dict = upload_image(image_file, 4)
    if result["code"] == 0:
        res = {
            "success": 1,
            "message": "上传成功",
            "url": url_for(".get_about_image", image_name=result["data"]),
        }
    else:
        res = {"success": 0, "message": result["msg"]}
    return jsonify(res)


@main_bp.route("/about/image/<string:image_name>", methods=["GET"])
@csrf.exempt  # 此路由去除 csrf 保护
def get_about_image(image_name: str):
    """ 获取关于中的图片

    :param image_name: 图片名称
    """
    return get_local_image(
        Path.joinpath(current_app.config["MYZONE_IMAGE_ABOUT_DIR"], image_name)
    )

app/bp_main/templates/main/_about_sidebar.html
<div class="col-sm-4">
    <!--    传送门-->
    <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3">
        <div class="card-header bg-white px-0 sidebar-title-underline">
            <strong><i class="fa fa-paper-plane mr-2 f-17"></i>传送门</strong>
        </div>
        <div class="card-body px-0 pt-3">
            <div class="row text-center">
                <div class="col-sm-4 deliver-box">
                    <a href="https://github.com/albert-lii" target="_blank" title="站主的Github">
                        <img class="deliver-logo" alt="站主的github"
                             src="{{ url_for('static', filename='mysite/img/github.png') }}">
                    </a>
                </div>
                <div class="col-sm-4 deliver-box">
                    <a href="https://www.jianshu.com/u/fe3e28b3a55d" target="_blank" title="站主的简书">
                        <img class="deliver-logo" alt="站主的简书"
                             src="{{ url_for('static', filename='mysite/img/jianshu.png') }}">
                    </a>
                </div>
                <div class="col-sm-4 deliver-box">
                    <a href="https://blog.csdn.net/liyi1009365545" target="_blank" title="站主的CSDN">
                        <img class="deliver-logo" alt="站主的CSDN"
                             src="{{ url_for('static', filename='mysite/img/csdn.png') }}">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--    微信公众号-->
    <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3">
        <div class="card-header bg-white px-0 sidebar-title-underline">
            <strong><i class="fa fa-weixin mr-2 f-17"></i>微信公众号</strong>
        </div>
        <div class="card-body px-0 pt-3">
            <div class="row text-center">
                <div class="col-sm-12 deliver-box">
                    <a href="" target="_blank" title="进入博主的Github查看博客源码">
                        <img class="deliver-logo" alt="站主的github"
                             src="{{ url_for('static', filename='mysite/img/qrcode-wechat-igank.jpg') }}">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--    赞助-->
    <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3">
        <div class="card-header bg-white px-0 sidebar-title-underline">
            <strong><i class="fa fa-superpowers mr-2 f-17"></i>赞助本站</strong>
        </div>
        <div class="card-body px-0 pt-3">
            <div class="row text-center">
                <div class="col-sm-6 deliver-box" style="width: 100%; padding: 0px;">
                    <a title="支付宝赞助本站">
                        <img class="deliver-logo" alt="支付宝赞助本站"
                             src="{{ url_for('static', filename='mysite/img/alipay-code.png') }}">
                        <p class="mt-2" style="color: #555;">支付宝</p>
                    </a>
                </div>
                <div class="col-sm-6 deliver-box" style="width: 100%; padding: 0px;">
                    <a title="微信赞助本站">
                        <img class="deliver-logo" alt="微信赞助本站"
                             src="{{ url_for('static', filename='mysite/img/wxpay-code.png') }}">
                        <p class="mt-2" style="color: #555;">微信</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/bp_main/templates/main/_articles.html
<!--如果有文章-->
{% if articles %}
<div>
    {% for article in articles %}
    <article class="excerpt">
        <header>
            <a class="label label-important" href="">{{ article.category.name }}<i class="label-arrow"></i></a>
            <h2>
                <a target="_blank" href="{{ url_for('work.show_article', article_id=article.id) }}?from={{ func_id }}">{{
                    article.title
                    }}</a>
            </h2>
        </header>
        <div class="content">
            {% if article.cover_url %}
            <div class="cover">
                <img class="cover" src="{{ article.cover_url }}"/>
            </div>
            {% endif %}
            {# striptags: 渲染之前把值中所有的HTML标签都删掉 #}
            {# truncate: 截取指定长度的字符串，默认长度为255 #}
            <div class="note">
                {% if article.cover_url %}
                <p class="text">{{ article.body_html|striptags|truncate(150) }}</p>
                {% else %}
                <p class="text">{{ article.body_html|striptags|truncate(300) }}</p>
                {% endif %}
            </div>
        </div>
        <p class="auth-info">
            <span class="muted"><i class="fa fa-user"></i>{{ article.author.username }}</span>
            <span class="muted"><i class="fa fa-clock-o"></i>{% if article.update %}{{ timestamp_to_strftime(article.update_time) }}{% else %}{{ timestamp_to_strftime(article.create_time) }}{% endif %}</span>
            <span class="muted"><i class="fa fa-eye"></i>{{ article.read_count }}浏览</span>
            <span class="muted"><i class="fa fa-comments-o"></i>{{ article.comments|length }}评论</span>
            <span class="muted"><i class="fa fa-heart-o"></i>
                <span class="count">{{ article.likes|length }}</span>喜欢
            </span>
        </p>
    </article>
    {% endfor %}
</div>

<!--如果沒有文章-->
{% else %}
<div class="tip">
    {% if channel_id != -1%}
    <h5>文章君已经在赶来的路上喽，看官稍后再来吧！(づ￣ 3￣)づ </h5>
    {% else %}
    <h5>抱歉，你要找的文章不住在这哦！( ´◔ ‸◔`)</h5>
    {% endif %}
</div>
{% endif %}

app/bp_main/templates/main/_banner.html
{% if banners %}
<div id="banner" class="carousel slide" style="margin-bottom: 0.71rem;" data-ride="carousel">
    <!-- 指示符 -->
    <ul class="carousel-indicators">
        {% for i in range(banners|length) %}
        {% if i == 0 %}
        <li data-target="#banner" data-slide-to="{{ i }}" class="active"></li>
        {% else %}
        <li data-target="#banner" data-slide-to="{{ i }}"></li>
        {% endif %}
        {% endfor %}
    </ul>
    <!-- 轮播图片 -->
    <div class="carousel-inner">
        {% if banners %}
        {% for i in range(banners|length) %}
        {% if i == 0 %}
        <div class="carousel-item active">
            <a target="_blank" href="{{ banners[i].link_url }}">
                <img class="banner-image" src="{{ banners[i].image_url }}">
            </a>
        </div>
        {% else %}
        <div class="carousel-item">
            <a target="_blank" href="{{ banners[i].link_url }}">
                <img class="banner-image" src="{{ banners[i].image_url }}">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    <!-- 左右切换按钮 -->
    <a class="carousel-control-prev" href="#banner" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#banner" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>
{% endif %}

app/bp_main/templates/main/about.html
{% extends 'base.html' %}

{% block title %}iGank - 关于本站{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.min.css') }}"/>
<link rel="stylesheet" href="{{ url_for('work.static',filename='css/article.css') }}"/>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-8">
            <div id="article-content">
                <textarea style="display:none;">{{ site_desc.body }}</textarea>
            </div>
        </div>
        {% include 'main/_about_sidebar.html' %}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/marked.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/prettify.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/raphael.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/underscore.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/sequence-diagram.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/flowchart.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/lib/jquery.flowchart.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='editormd/editormd.js') }}"></script>
<script type="text/javascript">
$(function(){
    var myEditor;
    myEditor = editormd.markdownToHTML("article-content", {
        htmlDecode: "style,script,iframe",
        emoji: true,
        taskList: true,
        tocm: true,
        tex: true, // 默认不解析
        flowChart: true, // 默认不解析
        sequenceDiagram: true, // 默认不解析
        codeFold: true
    });
});
</script>
{% endblock %}

app/bp_main/templates/main/edit_about.html
{% extends 'base.html' %}

{% block title %}iGank - 编辑关于{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.min.css') }}"/>
<link rel="stylesheet" href="{{ url_for('work.static',filename='css/edit_article.css') }}"/>
{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="form-group">
        <div id="my-editormd" class="form-control">
            {{ form.body(style="display:none;") }}
        </div>
    </div>
    <div class="form-group pull-right">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static',filename='editormd/editormd.js') }}"></script>
<script type="text/javascript">
$(function () {
    // markdown 插件
    editormd("my-editormd", {
        // width: "100%",
        height: "calc(100vh - 6rem)",
        syncScrolling: "single",
        path: "{{ url_for('static',filename='editormd/lib/') }}",
        codeFold: true,
        saveHTMLToTextarea: true, // 保存 HTML 到 Textarea
        searchReplace: true,
        htmlDecode : "style,script,iframe|on*", // 开启 HTML 标签解析，为了安全性，默认不开启
        emoji: true,
        taskList: true,
        tocm: true, // Using [TOCM]
        tex : true, // 开启科学公式TeX语言支持，默认关闭
        flowChart: true, // 开启流程图支持，默认关闭
        sequenceDiagram: true, // 开启时序/序列图支持，默认关闭,
        imageUpload: true, // 上传图片
        imageFormats: [ "jpg", "jpeg", "gif", "png", "bmp", "webp" ],
        // 上传图片时指定调用后台的视图函数
        imageUploadURL : "{{ url_for('main.upload_about_image') }}"
    });
});
</script>
{% endblock %}

{% block footer %}{% endblock %}

app/bp_main/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}iGank - 首页{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('main.static', filename='css/main.css') }}" type="text/css">
{% endblock%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            {% include 'main/_banner.html' %}
            {% include 'main/_articles.html' %}
            {% if articles %}
            <div class="page-pagination">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        {% include '_sidebar.html' %}
    </div>
</div>
{% endblock %}